version: '3'
services:
  adressbuch1854-client:
    image: ddmr/cake-php
    restart: always
    ports:
      - "80:80"

  adressbuch1854-database:
     image: mysql:latest
     command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default_authentication_plugin=mysql_native_password
     restart: always
     ports:
       - "3306:3306"
     environment:
        MYSQL_DATABASE: 'adressbuch1854'
        MYSQL_USER: 'dhip'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
     security_opt:
       - seccomp:unconfined
